version: "3.9"

services:
  evolution-api:
    container_name: evolution-api
    image: devlikeapro/whatsapp-api
    restart: always
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - WHATSAPP_API_KEY=${EVOLUTION_API_KEY}
    volumes:
      - ./instances:/app/instances
    networks:
      - evolution-net

networks:
  evolution-net:
    driver: bridge
